### ISSUE TITLE
JSON Viewer in VuGen

### ISSUE THREAD

**Issue by wilsonmar** [HPSoftware/VuGenPowerPack#6]
How about a viewer for JSON, which is much more prevalent now than XML.

Examples:
http://codebeautify.org/jsonviewer
https://www.jsoneditoronline.org/
http://jsonviewer.stack.hu/

It would be great to edit JSON stored in scripts or JSON files brought in dynamically during runs.

**Comment by BorisKozo** [comment]
I cannot elaborate about it but expect something in this direction in the next official version of LoadRunner. If you want to hear more then email me :)
